train_config:
  adam_beta1: 0.9
  adam_beta2: 0.95
  batch_size: 500000
  dropout_prob: 0.1
  eval_step: 256
  global_gradient_norm: 1.0
  learning_rate_decay: 0.1
  max_learning_rate: 6.0e-4
  warmup_steps: 500
  weight_decay: 0.1
model_config:
  n_heads: 12
  n_layers: 12
  block_size: 2048
  vocab_size: 50000
  separator_token: </s>
  tokenizer_path: "./chemlactica/tokenizer/ChemLacticaTokenizer66"
