train_config:
  adam_beta1: 0.9
  adam_beta2: 0.95
  batch_size: 500000
  dropout_prob: 0.1
  eval_step: 256
  global_gradient_norm: 1.0
  learning_rate_decay: 0.1
  max_learning_rate: 5.0e-4
  warmup_steps: 500
  weight_decay: 0.1
  bf16: true
  bf16_full_eval: true
  fp16: false
  tf32: true
  evaluation_strategy: "no"
  save_total_limit: 10
  grad_accumulation_scheduler: true
  dynamic_grad_accumulation: false
  grad_accumulation_patience: 4000
  grad_accumulation_max: 256
  grad_accumulation_delta_steps: 100
  grad_accumulation_delta_percentage: 0.02
model_config:
  n_heads: 12
  n_layers: 18
  block_size: 2048
  vocab_size: 256000
  separator_token: <bos>
  tokenizer_path: "./chemlactica/tokenizer/GemmaTokenizer"
