name: Run unittests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
    - name: Create Conda Environment
      shell: bash -l {0}
      run: |
       conda create --name cl11.7 python=3.10
       conda activate cl11.7
       conda install pytorch=2.0.1 pytorch-cuda=11.7 -c pytorch -c nvidia --solver libmamba
       conda install -c conda-forge cudatoolkit-dev==11.7 --solver libmamba
       nvcc --version
       pip3 install packaging
       pip3 install ninja
       pip3 install flash-attn --no-build-isolation
       pip3 install --upgrade datasets # the latest version is installed
       pip3 install transformers==4.31.0
       pip3 install accelerate==0.21.0
       pip3 install aim==3.17.5
       pip3 install pyyaml

    - name: Run unittests
      shell: bash -l {0}
      run: |
        conda activate cl11.7
        python3 confirm_tests.py --confirm
